### ISSUE TITLE
Pesach VII (on Shabbat) has no Hebrew translation

### ISSUE THREAD

**Issue by SLaks** [hebcal/hebcal-leyning#462]
[Demo](https://jsbin.com/batihup/edit?js,console):

```js
  name: [object Object] {
    en: "Pesach VII (on Shabbat)",
    he: undefined
  },
```

The last day is also missing translation

**Comment by mjradwin** [comment]
Thanks for the bug report and pull request. I may end up refactoring this and moving these strings and a bunch more from https://github.com/hebcal/hebcal-es6/blob/main/po/he.po to a dedicated `he.po` file in the `hebcal-leyning` repo. 

That would reduce bundle size a bit for `@hebcal/core` users who don't also need the leyning, but it won't make a huge difference because `@hebcal/core` is already gigantic due to the dependencies that Zmanim pulls in...
